// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_S8WdGor5vZx60MvdJi7EugWhNdm2ws',
    appId: '1:437393268639:web:9715d7b87c3af8cc81e7aa',
    messagingSenderId: '437393268639',
    projectId: 'appbiblioteca-7c279',
    authDomain: 'appbiblioteca-7c279.firebaseapp.com',
    storageBucket: 'appbiblioteca-7c279.firebasestorage.app',
    measurementId: 'G-9WHPD1ZM2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsskWAkbk9mV3kJG0CNpLl9jIUtoCx5Es',
    appId: '1:437393268639:android:1d25b9c847854e8d81e7aa',
    messagingSenderId: '437393268639',
    projectId: 'appbiblioteca-7c279',
    storageBucket: 'appbiblioteca-7c279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzAMW1knrsn6oIAtJvfFZcSCoX3tU6fRY',
    appId: '1:437393268639:ios:39814efbfd1f04e581e7aa',
    messagingSenderId: '437393268639',
    projectId: 'appbiblioteca-7c279',
    storageBucket: 'appbiblioteca-7c279.firebasestorage.app',
    iosBundleId: 'com.example.appBiblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzAMW1knrsn6oIAtJvfFZcSCoX3tU6fRY',
    appId: '1:437393268639:ios:39814efbfd1f04e581e7aa',
    messagingSenderId: '437393268639',
    projectId: 'appbiblioteca-7c279',
    storageBucket: 'appbiblioteca-7c279.firebasestorage.app',
    iosBundleId: 'com.example.appBiblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7_S8WdGor5vZx60MvdJi7EugWhNdm2ws',
    appId: '1:437393268639:web:8780eab3f908671d81e7aa',
    messagingSenderId: '437393268639',
    projectId: 'appbiblioteca-7c279',
    authDomain: 'appbiblioteca-7c279.firebaseapp.com',
    storageBucket: 'appbiblioteca-7c279.firebasestorage.app',
    measurementId: 'G-644PXWRNKR',
  );

}